### ISSUE TITLE
Edit on GitHub link broken

### ISSUE THREAD

**Issue by loeiten** [tqdm/tqdm.github.io#1]
The [Edit on GitHub](https://github.com/tqdm/tqdm.github.io/blob/master/index.html#L218) is broken.
Was the intention that the link should point to
https://github.com/tqdm/tqdm.github.io/edit/master/index.html?

**Comment by casperdcl** [comment]
That's the default edit link for github pages - I agree in this case it's not particularly helpful. Might just remove it completely or replace with "[View on GitHub](https://github.com/tqdm/tqdm/)"

**Comment by casperdcl** [comment]
fixed by 65d1b2a
