### ISSUE TITLE
Edit on GitHub button broken

### ISSUE THREAD

**Issue by rdimaio** [tqdm/tqdm.github.io#3]
Hi, the `Edit on GitHub` button at the top right of the page links leads to [here](https://github.com/tqdm/tqdm/edit/master/docs/index.md), which doesn't exist on GH. #1 mentions that the button was changed to say `View on GitHub` but it seems that it's back to saying `Edit on GitHub` now.

![image](https://user-images.githubusercontent.com/35903974/78503959-9795c580-779c-11ea-964b-36659558b915.png)

**Comment by casperdcl** [comment]
fixed by 65d1b2a
